CREATE DATABASE wedding;
USE wedding;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


--
-- Table structure for table 'user'
--

DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id int NOT NULL AUTO_INCREMENT,
  username varchar(100) DEFAULT NULL,
  email varchar(100) DEFAULT NULL,
  password varchar(500) DEFAULT NULL,
  name varchar(1000) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY username (username)
);

--
-- Table structure for table 'guest'
--

DROP TABLE IF EXISTS guest;

CREATE TABLE guest (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(1000) DEFAULT NULL,
  userId int NOT NULL,
  isAttending tinyint(1) DEFAULT NULL,
  hasResponded tinyint(1) DEFAULT NULL,
  song varchar(1000) DEFAULT NULL,
  foodPreferences varchar(1000) DEFAULT NULL,
  nonAlcoholic tinyint(1) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY userId (userId),
  CONSTRAINT `guest_ibfk_1` FOREIGN KEY (userId) REFERENCES user (id)
);

--
-- Dumping data for table 'user'
--

LOCK TABLES user WRITE;
/*!40000 ALTER TABLE user DISABLE KEYS */;
INSERT INTO user VALUES (1,'admin','','pbkdf2:sha256:1000000$YtugNFDvdymjGeHe$aec6446fe487c87f562256109f68f842c5854cb5fd793e8593d4d662c9232200','admin');
/*!40000 ALTER TABLE user ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;





