version: '3'
services:
  #Registry
  registry:
    image: registry:2
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - registrydata:/data

#Volumes
volumes:
  registrydata:
    name: registrydata
    external: true