version: "3.9"
services:
  web:
    container_name: wedding-ui
    image: banaj-johansson.se:5000/wedding-web:latest
    restart: unless-stopped
    ports:
      - "8004:8001"
    environment:
      - DB_PASSWORD=OKnZHcWzKDzHxPp0UbgJ
      - DB_HOST=db
      - DB_PORT=3306
      - SMTP_PASSWORD=
      - SMTP_USERNAME=
      - SMTP_SERVER=
      - SECRET_KEY=
    networks:
      - wedding-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  db:
    hostname: db
    container_name: wedding-db
    image: wedding-mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=OKnZHcWzKDzHxPp0UbgJ
    volumes:
      - wedding-db:/var/lib/mysql
    networks:
      - wedding-net

volumes:
  wedding-db:
    name: "wedding-db"
    external: true

networks:
  wedding-net:
    driver: bridge
